/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import conection.Conexion;
import controlador.Controlador;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.modelo;

/**
 *
 * @author leoxi
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        setIconImage(new ImageIcon(getClass().getResource("/images/icono-cerebro.png")).getImage());
        setTitle("Mate PRO");
        initComponents();
        this.setLocationRelativeTo(this);
        btnIngresar.hide();
        ctrl.escribiLog("mostre el login");
    }
    modelo model = new modelo();
    VISTA view = new vista.VISTA();
    Controlador ctrl = new Controlador(view, model);
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUser = new javax.swing.JTextField();
        jPass = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        lblFondo_Login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(376, 428));
        setMinimumSize(new java.awt.Dimension(376, 428));
        setName("frLogin"); // NOI18N
        setPreferredSize(new java.awt.Dimension(376, 428));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUser.setText("USUARIO");
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserKeyTyped(evt);
            }
        });
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 220, 40));

        jPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPass.setText("CONTRASEÑA");
        jPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPassFocusLost(evt);
            }
        });
        jPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPassMouseClicked(evt);
            }
        });
        jPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPassKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPassKeyTyped(evt);
            }
        });
        getContentPane().add(jPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 220, 40));

        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 110, 40));

        lblFondo_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFondo_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerebor-colores.png"))); // NOI18N
        lblFondo_Login.setName(""); // NOI18N
        getContentPane().add(lblFondo_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        String valueTxtPass = jPass.getText();
        if (valueTxtPass.equals("USUARIO") || valueTxtPass.equals("")) {
            jPass.setText("CONTRASEÑA");
        }
        txtUser.setText("");
    }//GEN-LAST:event_txtUserMouseClicked

    private void jPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPassMouseClicked
        String valueTxtUser = txtUser.getText();
        if (valueTxtUser.equals("USUARIO") || valueTxtUser.equals("")) {
            txtUser.setText("INGRESE SU USUARIO");
        }
        jPass.setText("");
    }//GEN-LAST:event_jPassMouseClicked

    private void jPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPassFocusLost
        ctrl.escribiLog("Active el botón ingresar");
    }//GEN-LAST:event_jPassFocusLost

    private void jPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassKeyTyped
        btnIngresar.show();
    }//GEN-LAST:event_jPassKeyTyped

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String sql = "", userCons="",idCons="", scoreCons="",  nombreCons="", passCons="", txtuser="",txtpass="";
        txtuser = txtUser.getText();
        txtpass = jPass.getText();
        String res = String.valueOf(txtpass.hashCode());
        sql = "SELECT * FROM users WHERE email = '"+txtuser+"'"; 
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                idCons = rs.getString("id");
                userCons = rs.getString("email");
                nombreCons = rs.getString("nombre");
                passCons = rs.getString("Password");
                scoreCons = rs.getString("score");
            }
        } catch (SQLException ex) {
//            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "excepcion "+ex,"ERROR EN SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
        if(userCons.equals(txtuser) && passCons.equals(res)){
            ctrl.iniciar();
            ctrl.escribiLog("Click en el botón ingresar");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Las credenciales no coinciden","ERROR EN SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void jPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String sql = "", userCons="",idCons="", scoreCons="",  nombreCons="", passCons="", txtuser="",txtpass="";
            txtuser = txtUser.getText();
            txtpass = jPass.getText();
            String res = String.valueOf(txtpass.hashCode());

            sql = "SELECT * FROM users WHERE email = '"+txtuser+"'";
            try {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    idCons = rs.getString("id");
                    userCons = rs.getString("email");
                    nombreCons = rs.getString("nombre");
                    passCons = rs.getString("Password");
                    scoreCons = rs.getString("score");
                }
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(userCons.equals(txtuser) && passCons.equals(res)){
                ctrl.iniciar();
                ctrl.escribiLog("key Enter presed en el botón ingresar");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Las credenciales no coinciden","ERROR EN SISTEMA", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jPassKeyPressed

    private void jPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPassFocusGained
        String valueTxtUser = txtUser.getText();
        if (valueTxtUser.equals("USUARIO") || valueTxtUser.equals("")) {
            txtUser.setText("INGRESE SU USUARIO");
        }
        jPass.setText("");
    }//GEN-LAST:event_jPassFocusGained

    private void txtUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JPasswordField jPass;
    private javax.swing.JLabel lblFondo_Login;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
Conexion ct = new Conexion();
    Connection cn = ct.conectar();
}
