/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.ImageIcon;


/**
 *
 * @author user
 */
public class VISTA extends javax.swing.JFrame {

    /**
     * Creates new form VISTA
     */
    public VISTA() {
        setIconImage(new ImageIcon(getClass().getResource("/images/icono-cerebro.png")).getImage());        
        initComponents();
        lbl_A_N0.setVisible(false); lbl_B_N0.setVisible(false);
        lbl_A_N1.setVisible(false); lbl_B_N1.setVisible(false);
        lbl_A_N2.setVisible(false); lbl_B_N2.setVisible(false);
        lbl_A_N3.setVisible(false); lbl_B_N3.setVisible(false);
        lbl_A_N4.setVisible(false); lbl_B_N4.setVisible(false);
        lbl_A_N5.setVisible(false); lbl_B_N5.setVisible(false);
        lbl_A_N6.setVisible(false); lbl_B_N6.setVisible(false);
        lbl_A_N7.setVisible(false); lbl_B_N7.setVisible(false);
        lbl_A_N8.setVisible(false); lbl_B_N8.setVisible(false);
        lbl_A_N9.setVisible(false); lbl_B_N9.setVisible(false);
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Por = new javax.swing.JLabel();
        btnMultiplicar = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        lbl_A_N0 = new javax.swing.JLabel();
        lbl_A_N1 = new javax.swing.JLabel();
        lbl_A_N2 = new javax.swing.JLabel();
        lbl_A_N3 = new javax.swing.JLabel();
        lbl_A_N4 = new javax.swing.JLabel();
        lbl_A_N5 = new javax.swing.JLabel();
        lbl_A_N6 = new javax.swing.JLabel();
        lbl_A_N7 = new javax.swing.JLabel();
        lbl_A_N8 = new javax.swing.JLabel();
        lbl_A_N9 = new javax.swing.JLabel();
        lbl_B_N0 = new javax.swing.JLabel();
        lbl_B_N1 = new javax.swing.JLabel();
        lbl_B_N2 = new javax.swing.JLabel();
        lbl_B_N3 = new javax.swing.JLabel();
        lbl_B_N4 = new javax.swing.JLabel();
        lbl_B_N5 = new javax.swing.JLabel();
        lbl_B_N6 = new javax.swing.JLabel();
        lbl_B_N7 = new javax.swing.JLabel();
        lbl_B_N8 = new javax.swing.JLabel();
        lbl_B_N9 = new javax.swing.JLabel();
        lblFondo_Vista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(376, 428));
        setMinimumSize(new java.awt.Dimension(376, 428));
        setName("frmVista"); // NOI18N
        setPreferredSize(new java.awt.Dimension(376, 428));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Por.setBackground(new java.awt.Color(226, 226, 226));
        lbl_Por.setForeground(new java.awt.Color(226, 226, 226));
        lbl_Por.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Por.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/por_64.png"))); // NOI18N
        lbl_Por.setAlignmentY(0.0F);
        lbl_Por.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_Por.setName("lbl_Por"); // NOI18N
        getContentPane().add(lbl_Por, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 25, -1, -1));

        btnMultiplicar.setBackground(new java.awt.Color(226, 226, 226));
        btnMultiplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/igual_64.png"))); // NOI18N
        btnMultiplicar.setToolTipText("");
        btnMultiplicar.setBorderPainted(false);
        btnMultiplicar.setContentAreaFilled(false);
        btnMultiplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMultiplicar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMultiplicar.setMaximumSize(new java.awt.Dimension(68, 68));
        btnMultiplicar.setMinimumSize(new java.awt.Dimension(68, 68));
        btnMultiplicar.setName("btnMultiplicar"); // NOI18N
        btnMultiplicar.setPreferredSize(new java.awt.Dimension(68, 68));
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 68, 68));

        txtResultado.setEditable(false);
        txtResultado.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultado.setToolTipText("");
        txtResultado.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtResultado.setName("txtResultado"); // NOI18N
        getContentPane().add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 99, 190, 50));

        btn0.setBackground(new java.awt.Color(226, 226, 226));
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num0_64.png"))); // NOI18N
        btn0.setToolTipText("CERO");
        btn0.setBorder(null);
        btn0.setContentAreaFilled(false);
        btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn0.setName("btn0"); // NOI18N
        btn0.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num0_48.png"))); // NOI18N
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 64, 64));

        btn1.setBackground(new java.awt.Color(226, 226, 226));
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num1_64.png"))); // NOI18N
        btn1.setToolTipText("UNO");
        btn1.setBorder(null);
        btn1.setContentAreaFilled(false);
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1.setName("btn1"); // NOI18N
        btn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num1_48.png"))); // NOI18N
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 64, 64));

        btn2.setBackground(new java.awt.Color(226, 226, 226));
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num2_64.png"))); // NOI18N
        btn2.setToolTipText("DOS");
        btn2.setBorder(null);
        btn2.setContentAreaFilled(false);
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn2.setName("btn2"); // NOI18N
        btn2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num2_48.png"))); // NOI18N
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 64, 64));

        btn3.setBackground(new java.awt.Color(226, 226, 226));
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num3_64.png"))); // NOI18N
        btn3.setToolTipText("TRES");
        btn3.setBorder(null);
        btn3.setContentAreaFilled(false);
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn3.setName("btn3"); // NOI18N
        btn3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num3_48.png"))); // NOI18N
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 64, 64));

        btn4.setBackground(new java.awt.Color(226, 226, 226));
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num4_64.png"))); // NOI18N
        btn4.setToolTipText("CUATRO");
        btn4.setBorder(null);
        btn4.setContentAreaFilled(false);
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn4.setName("btn4"); // NOI18N
        btn4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num4_48.png"))); // NOI18N
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 64, 64));

        btn5.setBackground(new java.awt.Color(226, 226, 226));
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num5_64.png"))); // NOI18N
        btn5.setToolTipText("CINCO");
        btn5.setBorder(null);
        btn5.setContentAreaFilled(false);
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn5.setName("btn5"); // NOI18N
        btn5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num5_48.png"))); // NOI18N
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 64, 64));

        btn6.setBackground(new java.awt.Color(226, 226, 226));
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num6_64.png"))); // NOI18N
        btn6.setToolTipText("SEIS");
        btn6.setBorder(null);
        btn6.setContentAreaFilled(false);
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn6.setName("btn6"); // NOI18N
        btn6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num6_48.png"))); // NOI18N
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 64, 64));

        btn7.setBackground(new java.awt.Color(226, 226, 226));
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num7_64.png"))); // NOI18N
        btn7.setToolTipText("SIETE");
        btn7.setBorder(null);
        btn7.setContentAreaFilled(false);
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn7.setName("btn7"); // NOI18N
        btn7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num7_48.png"))); // NOI18N
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 64, 64));

        btn8.setBackground(new java.awt.Color(226, 226, 226));
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num8_64.png"))); // NOI18N
        btn8.setToolTipText("OCHO");
        btn8.setBorder(null);
        btn8.setContentAreaFilled(false);
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn8.setName("btn8"); // NOI18N
        btn8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num8_48.png"))); // NOI18N
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 64, 64));

        btn9.setBackground(new java.awt.Color(226, 226, 226));
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num9_64.png"))); // NOI18N
        btn9.setToolTipText("NUEVE");
        btn9.setBorder(null);
        btn9.setContentAreaFilled(false);
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn9.setName("btn9"); // NOI18N
        btn9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num9_48.png"))); // NOI18N
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 64, 64));

        lbl_A_N0.setBackground(new java.awt.Color(226, 226, 226));
        lbl_A_N0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_A_N0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num0_64.png"))); // NOI18N
        lbl_A_N0.setAlignmentY(0.0F);
        lbl_A_N0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_A_N0.setName("lbl_A_N0"); // NOI18N
        getContentPane().add(lbl_A_N0, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 25, 64, 64));

        lbl_A_N1.setBackground(new java.awt.Color(226, 226, 226));
        lbl_A_N1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_A_N1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num1_64.png"))); // NOI18N
        lbl_A_N1.setAlignmentY(0.0F);
        lbl_A_N1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_A_N1.setName("lbl_A_N1"); // NOI18N
        getContentPane().add(lbl_A_N1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 25, 64, 64));

        lbl_A_N2.setBackground(new java.awt.Color(226, 226, 226));
        lbl_A_N2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_A_N2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num2_64.png"))); // NOI18N
        lbl_A_N2.setAlignmentY(0.0F);
        lbl_A_N2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_A_N2.setName("lbl_A_N2"); // NOI18N
        getContentPane().add(lbl_A_N2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 25, 64, 64));

        lbl_A_N3.setBackground(new java.awt.Color(226, 226, 226));
        lbl_A_N3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_A_N3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num3_64.png"))); // NOI18N
        lbl_A_N3.setAlignmentY(0.0F);
        lbl_A_N3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_A_N3.setName("lbl_A_N3"); // NOI18N
        getContentPane().add(lbl_A_N3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 25, 64, 64));

        lbl_A_N4.setBackground(new java.awt.Color(226, 226, 226));
        lbl_A_N4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_A_N4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num4_64.png"))); // NOI18N
        lbl_A_N4.setAlignmentY(0.0F);
        lbl_A_N4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_A_N4.setName("lbl_A_N4"); // NOI18N
        getContentPane().add(lbl_A_N4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 25, 64, 64));

        lbl_A_N5.setBackground(new java.awt.Color(226, 226, 226));
        lbl_A_N5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_A_N5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num5_64.png"))); // NOI18N
        lbl_A_N5.setAlignmentY(0.0F);
        lbl_A_N5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_A_N5.setName("lbl_A_N5"); // NOI18N
        getContentPane().add(lbl_A_N5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 25, 64, 64));

        lbl_A_N6.setBackground(new java.awt.Color(226, 226, 226));
        lbl_A_N6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_A_N6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num6_64.png"))); // NOI18N
        lbl_A_N6.setAlignmentY(0.0F);
        lbl_A_N6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_A_N6.setName("lbl_A_N6"); // NOI18N
        getContentPane().add(lbl_A_N6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 25, 64, 64));

        lbl_A_N7.setBackground(new java.awt.Color(226, 226, 226));
        lbl_A_N7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_A_N7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num7_64.png"))); // NOI18N
        lbl_A_N7.setAlignmentY(0.0F);
        lbl_A_N7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_A_N7.setName("lbl_A_N7"); // NOI18N
        getContentPane().add(lbl_A_N7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 25, 64, 64));

        lbl_A_N8.setBackground(new java.awt.Color(226, 226, 226));
        lbl_A_N8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_A_N8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num8_64.png"))); // NOI18N
        lbl_A_N8.setAlignmentY(0.0F);
        lbl_A_N8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_A_N8.setName("lbl_A_N8"); // NOI18N
        getContentPane().add(lbl_A_N8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 25, 64, 64));

        lbl_A_N9.setBackground(new java.awt.Color(226, 226, 226));
        lbl_A_N9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_A_N9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num9_64.png"))); // NOI18N
        lbl_A_N9.setAlignmentY(0.0F);
        lbl_A_N9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_A_N9.setName("lbl_A_N9"); // NOI18N
        getContentPane().add(lbl_A_N9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 25, 64, 64));

        lbl_B_N0.setBackground(new java.awt.Color(226, 226, 226));
        lbl_B_N0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_B_N0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num0_64.png"))); // NOI18N
        lbl_B_N0.setName("lbl_B_N0"); // NOI18N
        getContentPane().add(lbl_B_N0, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 25, 64, 64));

        lbl_B_N1.setBackground(new java.awt.Color(226, 226, 226));
        lbl_B_N1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_B_N1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num1_64.png"))); // NOI18N
        lbl_B_N1.setName("lbl_B_N1"); // NOI18N
        getContentPane().add(lbl_B_N1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 25, 64, 64));

        lbl_B_N2.setBackground(new java.awt.Color(226, 226, 226));
        lbl_B_N2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_B_N2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num2_64.png"))); // NOI18N
        lbl_B_N2.setName("lbl_B_N2"); // NOI18N
        getContentPane().add(lbl_B_N2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 25, 64, 64));

        lbl_B_N3.setBackground(new java.awt.Color(226, 226, 226));
        lbl_B_N3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_B_N3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num3_64.png"))); // NOI18N
        lbl_B_N3.setName("lbl_B_N3"); // NOI18N
        getContentPane().add(lbl_B_N3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 25, 64, 64));

        lbl_B_N4.setBackground(new java.awt.Color(226, 226, 226));
        lbl_B_N4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_B_N4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num4_64.png"))); // NOI18N
        lbl_B_N4.setName("lbl_B_N4"); // NOI18N
        getContentPane().add(lbl_B_N4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 25, 64, 64));

        lbl_B_N5.setBackground(new java.awt.Color(226, 226, 226));
        lbl_B_N5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_B_N5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num5_64.png"))); // NOI18N
        lbl_B_N5.setName("lbl_B_N5"); // NOI18N
        getContentPane().add(lbl_B_N5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 25, 64, 64));

        lbl_B_N6.setBackground(new java.awt.Color(226, 226, 226));
        lbl_B_N6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_B_N6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num6_64.png"))); // NOI18N
        lbl_B_N6.setName("lbl_B_N6"); // NOI18N
        getContentPane().add(lbl_B_N6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 25, 64, 64));

        lbl_B_N7.setBackground(new java.awt.Color(226, 226, 226));
        lbl_B_N7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_B_N7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num7_64.png"))); // NOI18N
        lbl_B_N7.setName("lbl_B_N7"); // NOI18N
        getContentPane().add(lbl_B_N7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 25, 64, 64));

        lbl_B_N8.setBackground(new java.awt.Color(226, 226, 226));
        lbl_B_N8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_B_N8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num8_64.png"))); // NOI18N
        lbl_B_N8.setName("lbl_B_N8"); // NOI18N
        getContentPane().add(lbl_B_N8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 25, 64, 64));

        lbl_B_N9.setBackground(new java.awt.Color(226, 226, 226));
        lbl_B_N9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_B_N9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/black/Num9_64.png"))); // NOI18N
        lbl_B_N9.setName("lbl_B_N9"); // NOI18N
        getContentPane().add(lbl_B_N9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 25, 64, 64));

        lblFondo_Vista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFondo_Vista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerebor-colores.png"))); // NOI18N
        lblFondo_Vista.setName("lblFondo_Vista"); // NOI18N
        getContentPane().add(lblFondo_Vista, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMultiplicarActionPerformed
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VISTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VISTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VISTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VISTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new VISTA().setVisible(true);
////            }
////        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    public javax.swing.JButton btnMultiplicar;
    private javax.swing.JLabel lblFondo_Vista;
    public volatile javax.swing.JLabel lbl_A_N0;
    public volatile javax.swing.JLabel lbl_A_N1;
    public volatile javax.swing.JLabel lbl_A_N2;
    public volatile javax.swing.JLabel lbl_A_N3;
    public volatile javax.swing.JLabel lbl_A_N4;
    public volatile javax.swing.JLabel lbl_A_N5;
    public volatile javax.swing.JLabel lbl_A_N6;
    public volatile javax.swing.JLabel lbl_A_N7;
    public volatile javax.swing.JLabel lbl_A_N8;
    public volatile javax.swing.JLabel lbl_A_N9;
    public volatile javax.swing.JLabel lbl_B_N0;
    public volatile javax.swing.JLabel lbl_B_N1;
    public volatile javax.swing.JLabel lbl_B_N2;
    public volatile javax.swing.JLabel lbl_B_N3;
    public volatile javax.swing.JLabel lbl_B_N4;
    public volatile javax.swing.JLabel lbl_B_N5;
    public volatile javax.swing.JLabel lbl_B_N6;
    public volatile javax.swing.JLabel lbl_B_N7;
    public volatile javax.swing.JLabel lbl_B_N8;
    public volatile javax.swing.JLabel lbl_B_N9;
    private javax.swing.JLabel lbl_Por;
    public javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
